/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import javax.swing.JFrame;



/**
 *
 * @author Manuel
 */
public class NewJFrame extends javax.swing.JFrame {
    //JButton b=new JButton();
   
    
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        Titulo_Archivo = new javax.swing.JMenu();
        Titulo_Cargar = new javax.swing.JMenu();
        Perdidos = new javax.swing.JMenuItem();
        Encontrados = new javax.swing.JMenuItem();
        Adopcion = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Buscar_Coincidencias = new javax.swing.JMenuItem();
        Ver_Registros = new javax.swing.JMenu();
        Titulo_Formulario = new javax.swing.JMenu();
        Formulario_Maltrato_Animal = new javax.swing.JMenuItem();
        Titulo_Ayuda = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenuItem8.setText("jMenuItem8");

        jMenu7.setText("jMenu7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mascotas en red");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(700, 460));

        Titulo_Archivo.setText("Archivo");
        jMenuBar1.add(Titulo_Archivo);

        Titulo_Cargar.setText("Cargar");

        Perdidos.setText("Perdidos");
        Perdidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerdidosActionPerformed(evt);
            }
        });
        Titulo_Cargar.add(Perdidos);

        Encontrados.setText("Encontrados");
        Titulo_Cargar.add(Encontrados);

        Adopcion.setText("Adopción");
        Titulo_Cargar.add(Adopcion);
        Titulo_Cargar.add(jSeparator3);

        Buscar_Coincidencias.setText("Buscar coincidencias");
        Buscar_Coincidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buscar_CoincidenciasActionPerformed(evt);
            }
        });
        Titulo_Cargar.add(Buscar_Coincidencias);

        jMenuBar1.add(Titulo_Cargar);

        Ver_Registros.setText("Ver registros");
        jMenuBar1.add(Ver_Registros);

        Titulo_Formulario.setText("Formulario");

        Formulario_Maltrato_Animal.setText("Formulario de denuncia");
        Formulario_Maltrato_Animal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Formulario_Maltrato_AnimalActionPerformed(evt);
            }
        });
        Titulo_Formulario.add(Formulario_Maltrato_Animal);

        jMenuBar1.add(Titulo_Formulario);

        Titulo_Ayuda.setText("Ayuda");

        jMenuItem4.setText("Acerca de..");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        Titulo_Ayuda.add(jMenuItem4);

        jMenuBar1.add(Titulo_Ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerdidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerdidosActionPerformed
        JFrame j = new JFrame("Carga");
        j.setSize(300, 300);
        j.setLayout(null);
        j.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
        j.setVisible(true);
        
    }//GEN-LAST:event_PerdidosActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void Buscar_CoincidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buscar_CoincidenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Buscar_CoincidenciasActionPerformed

    private void Formulario_Maltrato_AnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Formulario_Maltrato_AnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Formulario_Maltrato_AnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Adopcion;
    private javax.swing.JMenuItem Buscar_Coincidencias;
    private javax.swing.JMenuItem Encontrados;
    private javax.swing.JMenuItem Formulario_Maltrato_Animal;
    private javax.swing.JMenuItem Perdidos;
    private javax.swing.JMenu Titulo_Archivo;
    private javax.swing.JMenu Titulo_Ayuda;
    private javax.swing.JMenu Titulo_Cargar;
    private javax.swing.JMenu Titulo_Formulario;
    private javax.swing.JMenu Ver_Registros;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
